export const QUESTIONS: string[] = [
  "What's something you've changed your mind about recently?",
  "What's a small thing that consistently makes you happy?",
  "If you could spend a week anywhere with no obligations, where?",
  "When you've moved cities, what's the thing you didn't expect to miss?",
  "What's the most you've ever surprised yourself?",
  "What does a perfect Sunday look like for you?",
  "What's a compliment you've never forgotten?",
  "Which version of yourself from the past would be most proud of you now?",
  "What's something you used to look for in a partner that you've completely let go of?",
  "What's a song that always pulls you somewhere else?",
  "When was the last time you felt completely present?",
  "What's something you're quietly proud of?",
  "Who taught you the most about love, and how?",
  "Is there a version of yourself that only exists in one specific place?",
  "What's a story your family always tells about you?",
  "What kind of old person do you want to be?",
  "What did you believe as a kid that turned out to be beautifully wrong?",
  "What's the kindest thing a stranger has ever done for you?",
  "What do you love about being the person watching others step into big moments, like weddings or graduations? What's harder about it?",
  "What do you do when no one is watching?",
  "What's a place you keep meaning to go back to?",
  "What's the bravest thing you've done that no one knows about?",
  "What's something you find unreasonably attractive?",
  "What's a birthday you remember as a turning point, even if no one else would have noticed?",
  "What's a hill you'd happily die on?",
  "What's a recurring dream you've had?",
  "What's the last thing that made you laugh until it hurt?",
  "What does home smell like?",
  "Is there someone in your family whose opinion of a partner matters most to you, and why them?",
  "What's a habit you'd like to keep for the rest of your life?",
  "When do you feel most like yourself?",
  "What's the most romantic thing you've ever witnessed?",
  "What would you do with an extra hour every day?",
  "What's a question you wish people asked you more often?",
  "What's something tiny that secretly delights you?",
  "What's something you've gotten more uncompromising about as you've gotten older?",
  "What's the best meal you've ever eaten, and who were you with?",
  "What's a piece of advice you ignored and shouldn't have?",
  "What's a piece of advice you took and shouldn't have?",
  "What did you want to be when you were ten?",
  "If we got to plan a perfect 24 hours together, anywhere, no logistics, what does the morning look like?",
  "What's a fear you've outgrown?",
  "What's a fear you're still working on?",
  "If we lived in the same house, what's the first thing we'd argue about?",
  "What's something you want to learn just because?",
  "What's a moment from this year you'd like to live again?",
  "What does being loved well look like to you?",
  "What's something you'd like me to know about you tonight?",
];

export type Pair = { a: { label: string; emoji: string }; b: { label: string; emoji: string } };

export const PAIRS: Pair[] = [
  { a: { label: "Mountains", emoji: "🏔️" }, b: { label: "Ocean", emoji: "🌊" } },
  { a: { label: "Coffee", emoji: "☕" }, b: { label: "Tea", emoji: "🍵" } },
  { a: { label: "Dogs", emoji: "🐶" }, b: { label: "Cats", emoji: "🐱" } },
  { a: { label: "Early bird", emoji: "🌅" }, b: { label: "Night owl", emoji: "🌙" } },
  { a: { label: "Planner", emoji: "🗓️" }, b: { label: "Spontaneous", emoji: "🎲" } },
  { a: { label: "Pizza for breakfast", emoji: "🍕" }, b: { label: "Cereal for dinner", emoji: "🥣" } },
  { a: { label: "Books", emoji: "📚" }, b: { label: "Films", emoji: "🎬" } },
  { a: { label: "City lights", emoji: "🌃" }, b: { label: "Starry sky", emoji: "✨" } },
  { a: { label: "Hot bath", emoji: "🛁" }, b: { label: "Long shower", emoji: "🚿" } },
  { a: { label: "Window seat", emoji: "🪟" }, b: { label: "Aisle seat", emoji: "💺" } },
  { a: { label: "Sweet", emoji: "🍯" }, b: { label: "Savory", emoji: "🧀" } },
  { a: { label: "Sunrise", emoji: "🌄" }, b: { label: "Sunset", emoji: "🌇" } },
  { a: { label: "Whisper", emoji: "🤫" }, b: { label: "Sing loud", emoji: "🎤" } },
  { a: { label: "Handwritten", emoji: "✍️" }, b: { label: "Voice note", emoji: "🎙️" } },
  { a: { label: "Big party", emoji: "🥂" }, b: { label: "Quiet dinner", emoji: "🕯️" } },
  { a: { label: "Road trip", emoji: "🛣️" }, b: { label: "Train ride", emoji: "🚆" } },
  { a: { label: "Paris", emoji: "🗼" }, b: { label: "Tokyo", emoji: "🗾" } },
  { a: { label: "Vinyl", emoji: "🎶" }, b: { label: "Live show", emoji: "🎸" } },
  { a: { label: "Slow dance", emoji: "💃" }, b: { label: "Walk at midnight", emoji: "🌙" } },
  { a: { label: "Texting", emoji: "💬" }, b: { label: "Calling", emoji: "📞" } },
  { a: { label: "Cabin in snow", emoji: "🏕️" }, b: { label: "Villa by sea", emoji: "🏖️" } },
  { a: { label: "Surprise gift", emoji: "🎁" }, b: { label: "Surprise trip", emoji: "✈️" } },
  { a: { label: "Hand on the small of the back", emoji: "🤲" }, b: { label: "Forehead kiss", emoji: "😘" } },
  { a: { label: "Italian", emoji: "🍝" }, b: { label: "Japanese", emoji: "🍣" } },
  { a: { label: "Rain on the roof", emoji: "🌧️" }, b: { label: "Snow falling", emoji: "❄️" } },
  { a: { label: "Tell the truth", emoji: "🫶" }, b: { label: "Keep the mystery", emoji: "🎭" } },
  { a: { label: "Read in bed", emoji: "📖" }, b: { label: "Talk in bed", emoji: "🛏️" } },
  { a: { label: "Camera roll full", emoji: "📷" }, b: { label: "Live in the moment", emoji: "🌿" } },
  { a: { label: "Cook together", emoji: "🍳" }, b: { label: "Order in", emoji: "🥡" } },
  { a: { label: "Fireplace", emoji: "🔥" }, b: { label: "Open window", emoji: "🌬️" } },
];

